LearnAzure.Admin/Controllers/Library_HighLevel/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

using LearnAzure.Admin;

namespace LearnAzure.Admin.Controllers
{
    public class CategoriesController : Controller
    {
        private MainDbContext db = new MainDbContext();

        // GET: Categories
        public ActionResult Index(int? sectionId = null)
        {
            ViewBag.Topics = new List<Topic>();

            if (sectionId == null || sectionId == 0)  return View(db.Categories.ToList());

            var section = db.Sections.Find(sectionId);
            var categories = db.Categories.Where(s => s.SectionId == section.Id).ToList();
            var exam = db.Exams.Find(section.ExamId);

            ViewBag.Title = $"{exam.Name} - {section.TitleAndNumber} - Categories";            
            ViewBag.Topics = db.Topics.AsEnumerable().Where(t => categories.Any(c => c.Id == t.CategoryId)).ToList();

            return View(categories);
        }


        // GET: Categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        
        // GET: Categories/Create
        public ActionResult Create(int? sectionId)
        {
            var section = db.Sections.Find(sectionId);

            // TODO: add number and full-number
            var category = new Category() { ExamId = section.ExamId, SectionId = sectionId.Value };

            return View(category);
        }


        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ExamId,SectionId,CategoryParts,PartNumber,CoverImage,Number,FullNumber,Title,CreatedAt,UpdatedAt,Version,UserAdded,IsComplete")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index", new { sectionId = category.SectionId });
            }

            return View(category);
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ExamId,SectionId,CategoryParts,PartNumber,CoverImage,Number,FullNumber,Title,CreatedAt,UpdatedAt,Version,UserAdded,IsComplete")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { sectionId = category.SectionId });
            }

            return View(category);
        }

        // GET: Categories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            
            db.Categories.Remove(category);
            db.SaveChanges();

            return RedirectToAction("Index", new { sectionId = category.SectionId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LearnAzure.Admin/Controllers/Library_HighLevel/TopicsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

using LearnAzure.Admin;

namespace LearnAzure.Admin.Controllers
{
    public class TopicsController : Controller
    {
        private MainDbContext db = new MainDbContext();

        // GET: Topics
        public ActionResult Index(int? categoryId = null, int? topicId = null)
        {
            if (categoryId == null || categoryId <= 0) return View(db.Topics.ToList());

            var topics = db.Topics.Where(t => t.CategoryId == categoryId).ToList();

            var category = db.Categories.Find(categoryId);
            var section = db.Sections.Find(category.Id);
            var exam = db.Exams.Find(section.ExamId);

            ViewBag.Title = $"{exam.Name} -> {section.TitleAndNumber} -> {category.TitleAndNumber} -> ";

            if (topicId == null) topicId = 1;

            /*
             *  public int SelectedTopicId { get; set; }
        public List<SelectListItem> DropDownTopics { get; set; } = new List<SelectListItem>();

        public List<Topic> Topics { get; set; } = new List<Topic>();
        public List<Question> Questions { get; set; } = new List<Question>();

        public Question NewQuestion { get; set; } = new Question();
             */

            var model = new TopicsViewModel()
            {
                SelectedTopicId = topicId.Value,
                DropDownTopics = topics.Select(t => new SelectListItem()
                {
                    Value = t.Id.ToString(),
                    Text = t.TitleAndNumber,
                }).ToList(),

                Topics = topics,
                Questions = db.Questions.Where(q => q.TopicId == topicId).ToList(),
            };

            return View(model);
        }


        // GET: Topics/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Topic topic = db.Topics.Find(id);
            if (topic == null)
            {
                return HttpNotFound();
            }
            return View(topic);
        }

        // GET: Topics/Create
        public ActionResult Create(int? categoryId)
        {
            var category = db.Categories.Find(categoryId);
            var section = db.Sections.First(s => s.Id == category.SectionId);
            var exam = db.Exams.First(e => e.Id == section.ExamId);

            var topic = new Topic()
            {
                ExamId = exam.Id,
                SectionId = section.Id,
                CategoryId = category.Id,
            };

            return View(topic);
        }

        // POST: Topics/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ExamId,SectionId,CategoryId,URL,DocumentationTitle,Tags,Number,FullNumber,Title,CreatedAt,UpdatedAt,Version,UserAdded,IsComplete")] Topic topic)
        {
            if (ModelState.IsValid)
            {
                db.Topics.Add(topic);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(topic);
        }


        public ActionResult AddQuestion(int topicId)
        {
            // TODO: clear questions form

            var categoryId = db.Topics.Where(t => t.Id == topicId).First().CategoryId;
            return RedirectToAction("Index", new { categoryId });
        }


        [HttpPost]
        public ActionResult RefreshQuestionsForTopic(TopicsViewModel model)
        {
            var topicId = model.SelectedTopicId;
            var categoryId = db.Topics.Where(t => t.Id == topicId).First().CategoryId;

            //if (Request.Form["AddQuestion"] != null)
                

            return RedirectToAction("Index", new { categoryId, topicId });

        }


        [HttpPost]
        public ActionResult NewOrEditQuestion(TopicsViewModel model)
        {
            var topicId = model.SelectedTopicId;
            var categoryId = db.Topics.Where(t => t.Id == topicId).First().CategoryId;

            // TODO: если 

            return RedirectToAction("Index", new { categoryId, topicId });
        }


        // GET: Topics/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Topic topic = db.Topics.Find(id);
            if (topic == null)
            {
                return HttpNotFound();
            }
            return View(topic);
        }

        // POST: Topics/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ExamId,SectionId,CategoryId,URL,DocumentationTitle,Tags,Number,FullNumber,Title,CreatedAt,UpdatedAt,Version,UserAdded,IsComplete")] Topic topic)
        {
            if (ModelState.IsValid)
            {
                db.Entry(topic).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(topic);
        }

        // GET: Topics/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Topic topic = db.Topics.Find(id);
            if (topic == null)
            {
                return HttpNotFound();
            }
            return View(topic);
        }

        // POST: Topics/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Topic topic = db.Topics.Find(id);
            db.Topics.Remove(topic);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LearnAzure.Admin/Views/Categories/Create.cshtml
@model LearnAzure.Admin.Category

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ExamId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExamId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExamId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SectionId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SectionId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SectionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryParts, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CategoryParts, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CategoryParts, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PartNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PartNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PartNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CoverImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CoverImage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CoverImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FullNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedAt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedAt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedAt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UpdatedAt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UpdatedAt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UpdatedAt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Version, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Version, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Version, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserAdded, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserAdded, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserAdded, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsComplete, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsComplete)
                    @Html.ValidationMessageFor(model => model.IsComplete, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a href="javascript:history.back()" title="Back To List">Back To List</a>
    @*<a href="javascript:history.back()" title="Back To List">Back To List</a>*@
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LearnAzure.Admin/Views/Categories/Delete.cshtml
@model LearnAzure.Admin.Category

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ExamId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExamId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SectionId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SectionId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CategoryParts)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryParts)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PartNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PartNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CoverImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CoverImage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FullNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Version)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Version)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserAdded)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserAdded)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsComplete)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsComplete)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a href="javascript:history.back()" title="Back To List">Back To List</a>
        </div>
    }
</div>

LearnAzure.Admin/Views/Categories/Details.cshtml
@model LearnAzure.Admin.Category

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ExamId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExamId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SectionId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SectionId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CategoryParts)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryParts)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PartNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PartNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CoverImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CoverImage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FullNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Version)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Version)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserAdded)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserAdded)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsComplete)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsComplete)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    <a href="javascript:history.back()" title="Back To List">Back To List</a>
</p>

LearnAzure.Admin/Views/Categories/Index.cshtml
@model IEnumerable<LearnAzure.Admin.Category>

@{  
}

<h2>@ViewBag.Title</h2>

<p>    
    <input type="button" class="btn btn-primary" style="width: 150px; margin-top: 20px; margin-bottom: 20px;"
           value="Add Category"
           onclick="location.href='@Url.Action("Create", "Categories", new { sectionId = Model.First().SectionId })'">
</p>

<table class="table">
    <tr>
        <th>
            # Category
        </th>
        <th>
            Topics
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CategoryParts)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PartNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CoverImage)
        </th>
        <th>
            Updated At
        </th>
        <th>
            User
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsComplete)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(item.TitleAndNumber, "Details", "Categories", new { id = item.Id }, null)
        </td>        
        <td>
            @foreach (var topic in ViewBag.Topics)
            {
                if (topic.CategoryId == item.Id)
                {
                    @Html.ActionLink((string)topic.TitleAndNumber, "Details", "Topics", new { id = item.Id }, new { target = "_blank" });
                    @:<br />
                }
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CategoryParts)
        </td>
        <td>
            @(item.PartNumber == 0 ? "" : item.PartNumber.ToString())

            @*@Html.DisplayFor(modelItem => item.PartNumber)*@
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CoverImage)
        </td>        
        <td>
            @Html.DisplayFor(modelItem => item.UpdatedAt)
        </td>        
        <td>
            @Html.DisplayFor(modelItem => item.UserAdded)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsComplete)
        </td>
        <td>
            @Html.ActionLink("Add Topic", "Create", "Topics", new { categoryId = item.Id }, new { @class = "link-success" }) |
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "link-dark" }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "link-danger" })            
        </td>
    </tr>
}

</table>