LearnAzure.Admin/ViewModels/TopicsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LearnAzure.Admin
{
    public class TopicsViewModel
    {
        [DisplayName("Topic")]
        public int SelectedTopicId { get; set; }
        public List<SelectListItem> DropDownTopics { get; set; } = new List<SelectListItem>();

        public List<Topic> Topics { get; set; } = new List<Topic>();
        public List<Question> Questions { get; set; } = new List<Question>();

        public Question NewQuestion { get; set; } = new Question();
    }
}

LearnAzure.Admin/Controllers/Library_HighLevel/TopicsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

using LearnAzure.Admin;

namespace LearnAzure.Admin.Controllers
{
    public class TopicsController : Controller
    {
        private MainDbContext db = new MainDbContext();

        // GET: Topics
        public ActionResult Index(int? categoryId = null, int? topicId = null)
        {
            if (categoryId == null || categoryId <= 0) return View(db.Topics.ToList());

            var topics = db.Topics.Where(t => t.CategoryId == categoryId).ToList();

            var category = db.Categories.Find(categoryId);
            var section = db.Sections.Find(category.Id);
            var exam = db.Exams.Find(section.ExamId);

            ViewBag.Title = $"{exam.Name} -> {section.TitleAndNumber} -> {category.TitleAndNumber} -> ";

            if (topicId == null) topicId = 1;

            /*
             *  public int SelectedTopicId { get; set; }
        public List<SelectListItem> DropDownTopics { get; set; } = new List<SelectListItem>();

        public List<Topic> Topics { get; set; } = new List<Topic>();
        public List<Question> Questions { get; set; } = new List<Question>();

        public Question NewQuestion { get; set; } = new Question();
             */

            var model = new TopicsViewModel()
            {
                SelectedTopicId = topicId.Value,
                DropDownTopics = topics.Select(t => new SelectListItem()
                {
                    Value = t.Id.ToString(),
                    Text = t.TitleAndNumber,
                }).ToList(),

                Topics = topics,
                Questions = db.Questions.Where(q => q.TopicId == topicId).ToList(),
            };

            return View(model);
        }


        // GET: Topics/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Topic topic = db.Topics.Find(id);
            if (topic == null)
            {
                return HttpNotFound();
            }
            return View(topic);
        }

        // GET: Topics/Create
        public ActionResult Create(int? categoryId)
        {
            var category = db.Categories.Find(categoryId);
            var section = db.Sections.First(s => s.Id == category.SectionId);
            var exam = db.Exams.First(e => e.Id == section.ExamId);

            var topic = new Topic()
            {
                ExamId = exam.Id,
                SectionId = section.Id,
                CategoryId = category.Id,
            };

            return View(topic);
        }

        // POST: Topics/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ExamId,SectionId,CategoryId,URL,DocumentationTitle,Tags,Number,FullNumber,Title,CreatedAt,UpdatedAt,Version,UserAdded,IsComplete")] Topic topic)
        {
            if (ModelState.IsValid)
            {
                db.Topics.Add(topic);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(topic);
        }


        public ActionResult AddQuestion(int topicId)
        {
            // TODO: clear questions form

            var categoryId = db.Topics.Where(t => t.Id == topicId).First().CategoryId;
            return RedirectToAction("Index", new { categoryId });
        }


        [HttpPost]
        public ActionResult RefreshQuestionsForTopic(TopicsViewModel model)
        {
            var topicId = model.SelectedTopicId;
            var categoryId = db.Topics.Where(t => t.Id == topicId).First().CategoryId;

            //if (Request.Form["AddQuestion"] != null)
                

            return RedirectToAction("Index", new { categoryId, topicId });

        }


        [HttpPost]
        public ActionResult NewOrEditQuestion(TopicsViewModel model)
        {
            var topicId = model.SelectedTopicId;
            var categoryId = db.Topics.Where(t => t.Id == topicId).First().CategoryId;

            // TODO: если 

            return RedirectToAction("Index", new { categoryId, topicId });
        }


        // GET: Topics/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Topic topic = db.Topics.Find(id);
            if (topic == null)
            {
                return HttpNotFound();
            }
            return View(topic);
        }

        // POST: Topics/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ExamId,SectionId,CategoryId,URL,DocumentationTitle,Tags,Number,FullNumber,Title,CreatedAt,UpdatedAt,Version,UserAdded,IsComplete")] Topic topic)
        {
            if (ModelState.IsValid)
            {
                db.Entry(topic).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(topic);
        }

        // GET: Topics/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Topic topic = db.Topics.Find(id);
            if (topic == null)
            {
                return HttpNotFound();
            }
            return View(topic);
        }

        // POST: Topics/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Topic topic = db.Topics.Find(id);
            db.Topics.Remove(topic);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LearnAzure.Admin/Controllers/Library_Questions/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

using LearnAzure.Admin;

namespace LearnAzure.Admin.Controllers
{
    public class QuestionsController : Controller
    {
        private MainDbContext db = new MainDbContext();

        // GET: Questions
        public ActionResult Index()
        {
            return View(db.Questions.ToList());
        }

        // GET: Questions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // GET: Questions/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Questions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ExamId,SectionId,CategoryId,TopicId,Type,QuestionText,Answer1,Answer2,Answer3,Answer4,Answer5,Answer6,CorrectAnswer,Explanation,ReferenceUrl,IsExamOnly,Number,FullNumber,Title,CreatedAt,UpdatedAt,Version,UserAdded,IsComplete")] Question question)
        {
            if (ModelState.IsValid)
            {
                db.Questions.Add(question);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(question);
        }

        // GET: Questions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // POST: Questions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ExamId,SectionId,CategoryId,TopicId,Type,QuestionText,Answer1,Answer2,Answer3,Answer4,Answer5,Answer6,CorrectAnswer,Explanation,ReferenceUrl,IsExamOnly,Number,FullNumber,Title,CreatedAt,UpdatedAt,Version,UserAdded,IsComplete")] Question question)
        {
            if (ModelState.IsValid)
            {
                db.Entry(question).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(question);
        }

        // GET: Questions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // POST: Questions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Question question = db.Questions.Find(id);
            db.Questions.Remove(question);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LearnAzure.Admin/Views/Topics/Create.cshtml
@model LearnAzure.Admin.Topic

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Topic</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ExamId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExamId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExamId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SectionId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SectionId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SectionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CategoryId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.URL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.URL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.URL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DocumentationTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DocumentationTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DocumentationTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tags, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tags, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tags, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FullNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedAt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedAt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedAt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UpdatedAt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UpdatedAt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UpdatedAt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Version, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Version, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Version, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserAdded, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserAdded, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserAdded, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsComplete, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsComplete)
                    @Html.ValidationMessageFor(model => model.IsComplete, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a href="javascript:history.back()" title="Back To List">Back To List</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LearnAzure.Admin/Views/Topics/Delete.cshtml
@model LearnAzure.Admin.Topic

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Topic</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ExamId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExamId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SectionId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SectionId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CategoryId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.URL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.URL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DocumentationTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DocumentationTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tags)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tags)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FullNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Version)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Version)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserAdded)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserAdded)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsComplete)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsComplete)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a href="javascript:history.back()" title="Back To List">Back To List</a>
        </div>
    }
</div>

LearnAzure.Admin/Views/Topics/Details.cshtml
@model LearnAzure.Admin.Topic

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Topic</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ExamId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExamId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SectionId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SectionId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CategoryId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.URL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.URL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DocumentationTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DocumentationTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tags)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tags)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FullNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Version)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Version)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserAdded)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserAdded)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsComplete)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsComplete)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    <a href="javascript:history.back()" title="Back To List">Back To List</a>
</p>

LearnAzure.Admin/Views/Topics/Index.cshtml
@model LearnAzure.Admin.TopicsViewModel

@{

}

<h2>@ViewBag.Title  <b>Topics</b></h2>

<p>
    <input type="button" class="btn btn-primary" style="width: 150px; margin-top: 20px; margin-bottom: 20px;"
           value="Add Topic"
           onclick="location.href='@Url.Action("Create", "Topics", new { categoryId = Model.Topics.First().CategoryId })'">
</p>
<table class="table">
    <tr>
        <th>
            # Topic
        </th>
        <th>
            Docs
        </th>
        <th>
            Tags
        </th>
        <th>
            Updated At
        </th>
        <th>
            User
        </th>
        <th>
            Is Complete
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.Topics)
    {
        <tr>
            <td>
                @Html.ActionLink(item.TitleAndNumber, "Details", "Topics", new { id = item.Id }, null)
            </td>
            <td>
                <a href="@item.URL" target="_blank">@item.DocumentationTitle</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tags)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UpdatedAt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserAdded)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsComplete)
            </td>
            <td>
                @Html.ActionLink("Add Question", "AddQuestion", "Topics", new { id = item.Id }, new { @class = "link-success" }) |
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "link-dark" }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "link-danger" })
            </td>
        </tr>
    }

</table>

<hr style="margin-top:30px; margin-bottom: 30px; color: black; height:3px;" />


<!-- Questions Table section -->
<h3>Questions</h3>


<div>
    <form class="form-horizontal" action="@Url.Action("RefreshQuestionsForTopic", "Topics")" method="post">

        <div class="form-group">
            @Html.LabelFor(m => m.SelectedTopicId, new { @class = "col-sm-2 control-label" })

            <div class="col-sm-5">
                @Html.DropDownListFor(m => m.SelectedTopicId, Model.DropDownTopics, new { @class = "form-control" })
            </div>
            <div class="col-sm-5">
                <input type="submit" class="btn btn-default" style="width: 120px;" id="AddQuestion" name="AddQuestion" value="Add Question">
                <input type="submit" class="btn btn-default" style="width: 100px;display:none;" id="LoadTopics" name="LoadTopics" value="Refresh">
            </div>
        </div>
    </form>
</div>


<!-- Questions for topic -->
<table class="table">
    <tr>
        <th>
            #
        </th>
        <th>
            Type
        </th>
        <th>
            Question
        </th>
        <th>
            Answer1
        </th>
        <th>
            Answer2
        </th>
        <th>
            Answer3
        </th>
        <th>
            Answer4
        </th>
        <th>
            Answer5
        </th>
        <th>
            Answer6
        </th>
        <th>
            Correct Answer
        </th>
        <th>
            For Exam
        </th>
        <th>
            Updated At
        </th>
        <th>
            User
        </th>
        <th>
            Is Complete
        </th>
    </tr>

    @foreach (var item in Model.Questions)
    {
        <tr>
            <td>
                @Html.ActionLink(item.TitleAndNumber, "Details", "Questions", new { id = item.Id }, null)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.QuestionText)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Answer1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Answer2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Answer3)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Answer4)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Answer5)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Answer6)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CorrectAnswer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsExamOnly)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UpdatedAt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserAdded)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsComplete)
            </td>
        </tr>
    }
</table>

<hr style="margin-top:30px; margin-bottom: 30px; color: black; height:3px;" />


<!-- Add/Edit question -->
<h3>Edit Question</h3>


<div>
    <form class="form-horizontal" action="@Url.Action("NewOrEditQuestion", "Topics")" method="post">

        <div class="form-group">
            @Html.LabelFor(m => m.SelectedTopicId, new { @class = "col-sm-2 control-label" })

            <div class="col-sm-5">
                @Html.DropDownListFor(m => m.SelectedTopicId, Model.DropDownTopics, new { @class = "form-control" })
            </div>
            <div class="col-sm-5">
                <input type="submit" class="btn btn-default" style="width: 120px;" id="AddQuestion" name="AddQuestion" value="Add Question">
                <input type="submit" class="btn btn-default" style="width: 100px;display:none;" id="LoadTopics" name="LoadTopics" value="Refresh">
            </div>
        </div>
    </form>
</div>


@section Scripts
{
    <script>
        $(document).on('change', '#SelectedTopicId', function () {
            $("#LoadTopics").click();
        });
                //$(document).ready(function () {
                        //});
    </script>
}